FROM node:17.3.0-alpine3.15

CMD [ "bin/sh" ]

ENV PROJECT /frontend

WORKDIR ${PROJECT}

RUN apk update && \
    npm install -g create-react-app \
    npm install react-router-dom@6 \
    npm install firebase \
    npm install styled-components \
    npm install axios \
    npm install recoil

ADD ${PROJECT}/package.json ${PROJECT}

RUN npm install