USE gibrary;

CREATE TABLE IF NOT EXISTS groupies (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(25) NOT NULL,
    introduce TEXT,
    max_people INT NOT NULL DEFAULT 50,
    group_key CHAR(32),
    is_opened BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)