USE gibrary;

CREATE TABLE IF NOT EXISTS categories (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    data VARCHAR(10) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO categories(data) VALUES("game");
INSERT INTO categories(data) VALUES("sport");
INSERT INTO categories(data) VALUES("work");
INSERT INTO categories(data) VALUES("other");