USE gibrary;

CREATE TABLE IF NOT EXISTS home_items (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    detail TEXT,
    is_opened BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)