USE gibrary;

CREATE TABLE IF NOT EXISTS options (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    is_opened BOOLEAN NOT NULL DEFAULT TRUE,
    lang VARCHAR(6) NOT NULL DEFAULT "ja_JP",
    switch_color CHAR(5) NOT NULL DEFAULT "white",
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
)