FROM golang:1.17-alpine

WORKDIR /usr/local/go/src/server

COPY server/go.mod .
COPY server/go.sum .
COPY server/.env .

RUN go mod download

COPY ./server .

WORKDIR /usr/local/go/src/server/cmd

CMD ["go", "run", "main.go"]